kill-trackman feature added

diff --git a/trackman-client b/trackman-client
--- a/trackman-client
+++ b/trackman-client
@@ -1,11 +1,44 @@
 #!/bin/bash
+
   #####  #####     ##     ####   #    #  #    #    ##    #    #
     #    #    #   #  #   #    #  #   #   ##  ##   #  #   ##   #
     #    #    #  #    #  #       ####    # ## #  #    #  # #  #
     #    #####   ######  #       #  #    #    #  ######  #  # #
     #    #   #   #    #  #    #  #   #   #    #  #    #  #   ##
     #    #    #  #    #   ####   #    #  #    #  #    #  #    #
+
+source trackman.conf
+
 if [ $# -le 1 ]
 then
     exit 1
 fi
+
+silent=1;
+for i in $*; do if [ "$i" = "--silent" ]; then silent=0; fi; done
+
+if [ ! $silent ]; then echo "starting to capture...."; fi
+./capture&
+if [ ! $silent ] && [ $? ]; then
+    echo "starting trackman-client.."
+elif [ ! $silent ]; then
+    echo "ERROR failed to capture.. Try again"
+    exit 1
+fi
+
+while [ 0 ]
+do
+    data=`sed -n '1p' $DUMP_FILE`
+    if [ ! $silent ]; then
+        ./client $1 $2 "$data" 2>/dev/null
+    else
+        ./client $1 $2 "$data" >/dev/null 2>/dev/null
+    fi
+    if [ $? ]; then
+        sed -n '2,$p' $DUMP_FILE > temp_dump
+        cat temp_dump >$DUMP_FILE
+        rm temp_dump
+    fi
+done
+#kill capture before exiting
+killall capture
